version: '3.1'
services:
  odoo_web:
#     add dev tool :
#    build: ./dockerfile/
    image: odoo:15

    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
      - ../extra-addons/odoo_api:/mnt/extra-addons/odoo_api
      - ../extra-addons/tibillet:/mnt/extra-addons/tibillet
      - ../extra-addons/vertical-association/membership_extension:/mnt/extra-addons/membership_extension
      - ../extra-addons/vertical-association/membership_variable_period:/mnt/extra-addons/membership_variable_period
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=odoo_db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    command: bash entrypoint.sh --dev reload
#    command: sleep 30d

  odoo_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "postgres"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
