version: '3.1'
services:
  odoo_web:
#     add dev tool :
#    build: ./dockerfile/
    image: odoo:15

    depends_on:
      - odoo_db
    ports:
      - 8069:8069
#    expose:
#      - 8069:8069
    volumes:
      - ../extra-addons/tibillet:/mnt/extra-addons/tibillet
#      - ../submodule/odoo_api:/mnt/extra-addons/odoo_api
      - ../submodule/vertical-association/membership_extension:/mnt/extra-addons/membership_extension
      - ../submodule/vertical-association/membership_variable_period:/mnt/extra-addons/membership_variable_period
#      - ../submodule/mis-builder/mis_builder:/mnt/extra-addons/mis_builder
#      - ../submodule/mis-builder/mis_builder_budget:/mnt/extra-addons/mis_builder_budget
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./bashrc:/var/lib/odoo/.bashrc
    environment:
      - HOST=odoo_db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
#    command: bash entrypoint.sh --dev reload
    command: sleep 30d

    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.odoo_15.tls.certresolver=tlsresolver
      - traefik.http.routers.odoo_15.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.odoo_15.entrypoints=websecure
      - traefik.http.services.odoo_15.loadbalancer.server.port=8069

    networks:
      - frontend
      - back_odoo15_db

  odoo_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "postgres"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - back_odoo15_db

networks:
  frontend:
    external: true
  back_odoo15_db:
    name: "back_odoo15_db"

