version: '3.1'
services:
  odoo_web:
#     add dev tool :
#    build: ./dockerfile/
    image: odoo:15

    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
      - ../extra-addons:/mnt/extra-addons
      - ../extra-addons/vertical-association/membership_extension:/mnt/extra-addons/membership_extension
      - ../extra-addons/vertical-association/membership_variable_period:/mnt/extra-addons/membership_variable_period
      - ../extra-addons/mis-builder/mis_builder:/mnt/extra-addons/mis_builder
      - ../extra-addons/mis-builder/mis_builder_budget:/mnt/extra-addons/mis_builder_budget
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=odoo_db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
#    command: bash entrypoint.sh --dev reload
    command: sleep 30d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.odoo_web.tls.certresolver=myresolver
      - traefik.http.routers.odoo_web.rule=Host(`${DOMAIN}`)
      - traefik.http.services.odoo_web.loadbalancer.server.port=8069
    networks:
      - frontend
      - back_odoo15_db


  odoo_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "postgres"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - back_odoo15_db



networks:
  frontend:
    external: true
  back_odoo15_db:
    name: "back_odoo15_db"

